name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Configure Docker for gcloud
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/your-spring-boot-app:$GITHUB_SHA .

      - name: Push Docker image
        run: docker push gcr.io/${{ secrets.GCP_PROJECT }}/your-spring-boot-app:$GITHUB_SHA

      - name: Deploy to GKE
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          kubectl set image deployment/your-deployment your-container=gcr.io/${{ secrets.GCP_PROJECT }}/your-spring-boot-app:$GITHUB_SHA
          kubectl rollout status deployment/your-deployment

      - name: Apply Service Configuration
        run: kubectl apply -f service.yml
