spring:
  banner:
    location: asciiBoot.txt
  profiles:
    active: prod

twelveDataAPIKey: ${TWELVE_DATA_API_KEY}
polygonAPIKey: ${POLYGON_API_KEY}

# TwelveData URLs
companyProfile: "https://api.twelvedata.com/profile?symbol={symbol}&apikey={apiKey}"
companyLogo: "https://api.twelvedata.com/logo?symbol={symbol}&apikey={apiKey}"
stockPrice: "https://api.twelvedata.com/price?symbol={symbol}&apikey={apiKey}"
previousClose: "https://api.twelvedata.com/eod?symbol={symbol}&&apikey={apiKey}"

# MongoDB
data:
  mongodb:
    uri: ${MONGODB_URI}
    database: ${MONGODB_DATABASE}

server:
  port: 8080