# Spring Boot Configuration
spring.profiles.active=prod
spring.springdoc.swagger-ui.path=/api-docs
spring.banner.location=asciiBoot.txt
logging.file.name=logs/app.log

# API Keys
twelveDataAPIKey=${TWELVE_DATA_API_KEY}
polygonAPIKey=${POLYGON_API_KEY}

# TwelveData URLs
companyProfile=https://api.polygon.io/v3/reference/tickers/{symbol}?apiKey={apiKey}
stockPrice=https://api.polygon.io/v2/last/nbbo/{symbol}?apikey={apiKey}
previousClose=https://api.polygon.io/v2/aggs/ticker/{symbol}/prev?unadjusted=true&apiKey={apiKey}

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE}