name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      # Inject secrets into application.properties (Dynamic configuration)
      - name: Inject Secrets into application.properties
        run: |
          sed -i "s|twelveDataAPIKey=.*|twelveDataAPIKey=${{ secrets.TWELVE_DATA_API_KEY }}|g" src/main/resources/application.properties
          sed -i "s|polygonAPIKey=.*|polygonAPIKey=${{ secrets.POLYGON_API_KEY }}|g" src/main/resources/application.properties
          sed -i "s|spring.data.mongodb.uri=.*|spring.data.mongodb.uri=${{ secrets.MONGODB_URI }}|g" src/main/resources/application.properties
          sed -i "s|spring.data.mongodb.database=.*|spring.data.mongodb.database=${{ secrets.MONGODB_DATABASE }}|g" src/main/resources/application.properties

      # Build the app with Gradle
      - name: Build with Gradle
        env:
          TWELVE_DATA_API_KEY: ${{ secrets.TWELVE_DATA_API_KEY }}
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
        run: ./gradlew build

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build --platform linux/arm64/v8 \
                       -t ${{ secrets.DOCKER_USERNAME }}/bullrun-service .

      # Push Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/bullrun-service